# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-27 12:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('pub_date', models.DateTimeField(primary_key=True, serialize=False, verbose_name='date published')),
                ('comment', models.CharField(max_length=200)),
                ('author', models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('pub_date', models.DateTimeField(primary_key=True, serialize=False, verbose_name='date published')),
                ('post_text', models.CharField(max_length=2000)),
                ('post_title', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='comments',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Posts'),
        ),
    ]
